/**
 * Demo mode: serves the intel API contract from a bundled warehouse snapshot
 * (src/data/demo/*.json, generated by backend/scripts/export_demo_snapshot.py).
 * Active whenever API_URL is not configured — e.g. a fresh Vercel import —
 * so the site works with real historical data and zero backend.
 *
 * Demo limits (by design, to keep the bundle small):
 *  - agency/company profiles: top-24 only (others return null -> friendly notice)
 *  - matchmaking floor: awards >= 10M SAR
 *  - pricing: activity x region cells with < 5 contracts are omitted
 */
import type {
  AgencyProfile, AgencyRow, CompanyProfile, CompanySearchRow, CompetitionRow,
  Lookups, MatchmakingRow, Overview, PricingBenchmark,
} from "@/lib/api";

import overviewJson from "@/data/demo/overview.json";
import lookupsJson from "@/data/demo/lookups.json";
import agenciesJson from "@/data/demo/agencies.json";
import agencyProfilesJson from "@/data/demo/agency_profiles.json";
import competitionJson from "@/data/demo/competition.json";
import matchmakingJson from "@/data/demo/matchmaking.json";
import companiesJson from "@/data/demo/companies.json";
import companyProfilesJson from "@/data/demo/company_profiles.json";
import pricingJson from "@/data/demo/pricing.json";

const agencies = agenciesJson as AgencyRow[];
const agencyProfiles = agencyProfilesJson as Record<string, AgencyProfile>;
const competition = competitionJson as CompetitionRow[];
const matchmaking = matchmakingJson as MatchmakingRow[];
const companies = companiesJson as CompanySearchRow[];
const companyProfiles = companyProfilesJson as Record<string, CompanyProfile>;
const pricing = pricingJson as Record<string, Omit<PricingBenchmark, "filters">>;

const EMPTY_BENCH: Omit<PricingBenchmark, "filters"> = {
  contracts: 0,
  avg_halalas: null, median_halalas: null, p25_halalas: null, p75_halalas: null,
  min_halalas: null, max_halalas: null, avg_sar: null, median_sar: null,
  avg_bidders: null,
};

export const demoApi = {
  overview: async (): Promise<Overview> => overviewJson as Overview,
  lookups: async (): Promise<Lookups> => lookupsJson as Lookups,

  agencies: async (sort = "spend", limit = 30): Promise<AgencyRow[]> => {
    const key = {
      spend: (a: AgencyRow) => a.total_award_sar ?? 0,
      tenders: (a: AgencyRow) => a.tenders,
      competition: (a: AgencyRow) => a.avg_bidders ?? 0,
    }[sort as "spend" | "tenders" | "competition"] ?? ((a: AgencyRow) => a.total_award_sar ?? 0);
    return [...agencies].sort((x, y) => key(y) - key(x)).slice(0, limit);
  },

  agencyProfile: async (id: number): Promise<AgencyProfile | null> =>
    agencyProfiles[String(id)] ?? null,

  pricing: async (params: URLSearchParams): Promise<PricingBenchmark> => {
    const aid = params.get("activity_id") ?? "";
    const rid = params.get("region_id") ?? "";
    const cell = pricing[`a${aid}|r${rid}`] ?? EMPTY_BENCH;
    return { ...cell, filters: { activity_id: aid || null, region_id: rid || null } };
  },

  competition: async (minTenders = 100, order = "least", limit = 30): Promise<CompetitionRow[]> => {
    const rows = competition.filter((r) => r.tenders >= minTenders);
    rows.sort((x, y) =>
      order === "least"
        ? (x.avg_bidders ?? 0) - (y.avg_bidders ?? 0)
        : (y.avg_bidders ?? 0) - (x.avg_bidders ?? 0),
    );
    return rows.slice(0, limit);
  },

  matchmaking: async (minAwardSar = 10_000_000, limit = 30): Promise<MatchmakingRow[]> =>
    matchmaking
      .filter((r) => (r.award_sar ?? 0) >= minAwardSar)
      .slice(0, limit),

  searchCompanies: async (q: string, limit = 30): Promise<CompanySearchRow[]> =>
    companies.filter((c) => c.name.includes(q)).slice(0, limit),

  companyProfile: async (id: number): Promise<CompanyProfile | null> =>
    companyProfiles[String(id)] ?? null,
};
